return {
  'ellisonleao/gruvbox.nvim',
  'folke/tokyonight.nvim',
  { 'nvim-treesitter/nvim-treesitter', build = ':TSUpdate' },
  'nvim-treesitter/nvim-treesitter-context',
  'williamboman/mason.nvim',
  'williamboman/mason-lspconfig.nvim',
  'neovim/nvim-lspconfig',
  'nvim-lua/plenary.nvim',
  'nvim-telescope/telescope.nvim',
  'kyazdani42/nvim-web-devicons',
  'kyazdani42/nvim-tree.lua',
  'mfussenegger/nvim-dap',
  'jose-elias-alvarez/null-ls.nvim',

  'hrsh7th/cmp-nvim-lsp',
  'hrsh7th/cmp-buffer',
  'hrsh7th/cmp-path',
  'hrsh7th/cmp-cmdline',
  'hrsh7th/nvim-cmp',
  'saadparwaiz1/cmp_luasnip',

  'L3MON4D3/LuaSnip',
  'rafamadriz/friendly-snippets',

  'windwp/nvim-autopairs',
  'github/copilot.vim',
  'mhartington/formatter.nvim',
  'APZelos/blamer.nvim',
  'mfussenegger/nvim-jdtls',
  'terrortylor/nvim-comment',
  'mrcjkb/haskell-tools.nvim',
}
